/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000334) */

(* top =  1  *)
(* src = "rtl/alu_8bit.v:1.1-88.10" *)
module alu_8bit(A, B, opcode, result, zero, carry, overflow);
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "rtl/alu_8bit.v:4.18-4.24" *)
  input [2:0] opcode;
  wire [2:0] opcode;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "rtl/alu_8bit.v:7.22-7.26" *)
  output zero;
  wire zero;
  (* src = "rtl/alu_8bit.v:8.22-8.27" *)
  output carry;
  wire carry;
  (* src = "rtl/alu_8bit.v:9.22-9.30" *)
  output overflow;
  wire overflow;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _000_;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _001_;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _002_;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _003_;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _004_;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _005_;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _006_;
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  wire _007_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _008_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _009_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _010_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _011_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _012_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _013_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _014_;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  wire _015_;
  (* src = "rtl/alu_8bit.v:8.22-8.27" *)
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  wire _131_;
  wire _132_;
  wire _133_;
  wire _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  wire _143_;
  wire _144_;
  wire _145_;
  wire _146_;
  wire _147_;
  wire _148_;
  wire _149_;
  wire _150_;
  wire _151_;
  wire _152_;
  wire _153_;
  wire _154_;
  wire _155_;
  wire _156_;
  wire _157_;
  wire _158_;
  wire _159_;
  wire _160_;
  wire _161_;
  wire _162_;
  wire _163_;
  wire _164_;
  wire _165_;
  wire _166_;
  wire _167_;
  wire _168_;
  wire _169_;
  wire _170_;
  wire _171_;
  wire _172_;
  wire _173_;
  wire _174_;
  wire _175_;
  wire _176_;
  wire _177_;
  wire _178_;
  wire _179_;
  wire _180_;
  wire _181_;
  wire _182_;
  wire _183_;
  wire _184_;
  wire _185_;
  wire _186_;
  wire _187_;
  wire _188_;
  wire _189_;
  wire _190_;
  wire _191_;
  wire _192_;
  wire _193_;
  wire _194_;
  wire _195_;
  wire _196_;
  wire _197_;
  wire _198_;
  wire _199_;
  wire _200_;
  wire _201_;
  wire _202_;
  wire _203_;
  wire _204_;
  wire _205_;
  wire _206_;
  wire _207_;
  wire _208_;
  wire _209_;
  wire _210_;
  wire _211_;
  wire _212_;
  wire _213_;
  wire _214_;
  wire _215_;
  wire _216_;
  wire _217_;
  wire _218_;
  wire _219_;
  wire _220_;
  wire _221_;
  wire _222_;
  wire _223_;
  wire _224_;
  wire _225_;
  wire _226_;
  wire _227_;
  wire _228_;
  wire _229_;
  wire _230_;
  wire _231_;
  wire _232_;
  wire _233_;
  wire _234_;
  wire _235_;
  wire _236_;
  wire _237_;
  wire _238_;
  wire _239_;
  wire _240_;
  wire _241_;
  wire _242_;
  wire _243_;
  wire _244_;
  wire _245_;
  wire _246_;
  wire _247_;
  wire _248_;
  wire _249_;
  wire _250_;
  wire _251_;
  wire _252_;
  wire _253_;
  wire _254_;
  wire _255_;
  wire _256_;
  wire _257_;
  wire _258_;
  wire _259_;
  wire _260_;
  wire _261_;
  wire _262_;
  wire _263_;
  wire _264_;
  wire _265_;
  wire _266_;
  wire _267_;
  wire _268_;
  wire _269_;
  wire _270_;
  wire _271_;
  wire _272_;
  wire _273_;
  wire _274_;
  wire _275_;
  wire _276_;
  wire _277_;
  wire _278_;
  wire _279_;
  wire _280_;
  wire _281_;
  wire _282_;
  wire _283_;
  (* src = "rtl/alu_8bit.v:4.18-4.24" *)
  wire _284_;
  (* src = "rtl/alu_8bit.v:4.18-4.24" *)
  wire _285_;
  (* src = "rtl/alu_8bit.v:4.18-4.24" *)
  wire _286_;
  (* src = "rtl/alu_8bit.v:9.22-9.30" *)
  wire _287_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _288_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _289_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _290_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _291_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _292_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _293_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _294_;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  wire _295_;
  (* src = "rtl/alu_8bit.v:7.22-7.26" *)
  wire _296_;
  (* src = "rtl/alu_8bit.v:31.24-31.61" *)
  wire _297_;
  (* src = "rtl/alu_8bit.v:42.24-42.58" *)
  wire _298_;
  wire _299_;
  wire _300_;
  wire _301_;
  wire _302_;
  wire _303_;
  wire [2:0] _304_;
  wire _305_;
  wire _306_;
  wire _307_;
  wire _308_;
  wire _309_;
  wire [3:0] _310_;
  wire [1:0] _311_;
  wire _312_;
  wire [3:0] _313_;
  wire [1:0] _314_;
  wire _315_;
  wire _316_;
  wire _317_;
  wire _318_;
  wire [1:0] _319_;
  wire _320_;
  wire _321_;
  wire [1:0] _322_;
  wire _323_;
  wire _324_;
  wire [1:0] _325_;
  wire _326_;
  wire [3:0] _327_;
  wire [1:0] _328_;
  wire _329_;
  wire [3:0] _330_;
  wire [1:0] _331_;
  wire _332_;
  wire [3:0] _333_;
  wire [1:0] _334_;
  wire _335_;
  wire [3:0] _336_;
  wire [1:0] _337_;
  wire _338_;
  wire [3:0] _339_;
  wire [1:0] _340_;
  wire _341_;
  wire [3:0] _342_;
  wire [1:0] _343_;
  wire _344_;
  wire [3:0] _345_;
  wire [1:0] _346_;
  wire _347_;
  wire [3:0] _348_;
  wire [1:0] _349_;
  wire _350_;
  wire _351_;
  wire _352_;
  wire _353_;
  wire _354_;
  wire _355_;
  wire _356_;
  wire _357_;
  wire _358_;
  wire _359_;
  wire _360_;
  wire _361_;
  wire _362_;
  wire _363_;
  wire _364_;
  wire _365_;
  wire _366_;
  wire _367_;
  wire _368_;
  wire _369_;
  wire _370_;
  wire _371_;
  wire _372_;
  wire _373_;
  wire _374_;
  wire _375_;
  wire _376_;
  wire _377_;
  wire _378_;
  wire _379_;
  wire _380_;
  wire _381_;
  wire _382_;
  wire _383_;
  wire _384_;
  wire _385_;
  wire _386_;
  wire _387_;
  wire _388_;
  wire _389_;
  wire _390_;
  wire _391_;
  wire _392_;
  wire _393_;
  wire _394_;
  wire _395_;
  wire _396_;
  wire _397_;
  wire _398_;
  wire _399_;
  wire _400_;
  wire _401_;
  wire _402_;
  wire _403_;
  wire _404_;
  wire _405_;
  wire _406_;
  wire _407_;
  wire _408_;
  wire _409_;
  wire _410_;
  wire _411_;
  wire _412_;
  wire _413_;
  wire _414_;
  wire _415_;
  wire _416_;
  wire _417_;
  wire _418_;
  wire _419_;
  wire _420_;
  wire _421_;
  wire _422_;
  wire _423_;
  wire _424_;
  wire _425_;
  wire _426_;
  wire _427_;
  (* src = "rtl/alu_8bit.v:75.23-75.32" *)
  wire _428_;
  (* src = "rtl/alu_8bit.v:39.22-39.27" *)
  wire _429_;
  (* src = "rtl/alu_8bit.v:31.25-31.39" *)
  wire _430_;
  (* src = "rtl/alu_8bit.v:52.22-52.27" *)
  wire [7:0] _431_;
  wire _432_;
  wire _433_;
  wire _434_;
  wire _435_;
  wire _436_;
  wire _437_;
  wire _438_;
  wire _439_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [8:0] _440_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [8:0] _441_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [8:0] _442_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [8:0] _443_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [8:0] _444_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [8:0] _445_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [8:0] _446_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [7:0] _447_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [7:0] _448_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _449_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _450_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _451_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [7:0] _452_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _453_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _454_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _455_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _456_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _457_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _458_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _459_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _460_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _461_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _462_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _463_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _464_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _465_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _466_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _467_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _468_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _469_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _470_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _471_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _472_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _473_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _474_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _475_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _476_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _477_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _478_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _479_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _480_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _481_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _482_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _483_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _484_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _485_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _486_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _487_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _488_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _489_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _490_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _491_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _492_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _493_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _494_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _495_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _496_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _497_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _498_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _499_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _500_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _501_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _502_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _503_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _504_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _505_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _506_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _507_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _508_;
  (* src = "rtl/alu_8bit.v:31.44-31.60" *)
  wire _509_;
  (* src = "rtl/alu_8bit.v:42.41-42.57" *)
  wire _510_;
  assign _215_ = ~_015_;
  assign _216_ = ~_004_;
  assign _217_ = ~_007_;
  assign _218_ = ~_001_;
  assign _219_ = ~_006_;
  assign _220_ = ~_002_;
  assign _221_ = ~_003_;
  assign _222_ = ~_005_;
  assign _223_ = ~_000_;
  assign _224_ = ~_286_;
  assign _225_ = ~_284_;
  assign _226_ = ~_285_;
  assign _227_ = _219_ | _014_;
  assign _228_ = _006_ ^ _014_;
  assign _229_ = _222_ | _013_;
  assign _230_ = _005_ & _013_;
  assign _231_ = _005_ | _013_;
  assign _232_ = _005_ ^ _013_;
  assign _233_ = ~_232_;
  assign _234_ = _216_ | _012_;
  assign _235_ = _004_ & _012_;
  assign _236_ = _004_ | _012_;
  assign _237_ = _004_ ^ _012_;
  assign _238_ = _221_ | _011_;
  assign _239_ = _003_ & _011_;
  assign _240_ = _003_ | _011_;
  assign _241_ = _003_ ^ _011_;
  assign _242_ = _220_ | _010_;
  assign _243_ = _002_ & _010_;
  assign _244_ = _002_ | _010_;
  assign _245_ = _002_ ^ _010_;
  assign _246_ = _218_ | _009_;
  assign _247_ = _001_ & _009_;
  assign _248_ = _001_ | _009_;
  assign _249_ = _001_ ^ _009_;
  assign _250_ = _000_ & _008_;
  assign _251_ = _000_ | _008_;
  assign _252_ = _000_ ^ _008_;
  assign _253_ = _223_ & _008_;
  assign _254_ = _249_ | _253_;
  assign _255_ = _246_ & _254_;
  assign _256_ = _245_ | _255_;
  assign _257_ = _242_ & _256_;
  assign _258_ = _241_ | _257_;
  assign _259_ = _238_ & _258_;
  assign _260_ = _237_ | _259_;
  assign _261_ = _234_ & _260_;
  assign _262_ = _232_ | _261_;
  assign _263_ = _229_ & _262_;
  assign _264_ = _284_ & _226_;
  assign _265_ = _224_ & _264_;
  assign _266_ = ~_265_;
  assign _267_ = _228_ | _263_;
  assign _268_ = _228_ ^ _263_;
  assign _269_ = _265_ & _268_;
  assign _270_ = ~_269_;
  assign _271_ = _248_ & _250_;
  assign _272_ = _247_ | _271_;
  assign _273_ = _245_ & _272_;
  assign _274_ = _243_ | _273_;
  assign _275_ = _241_ & _274_;
  assign _276_ = _239_ | _275_;
  assign _277_ = _237_ & _276_;
  assign _278_ = _235_ | _277_;
  assign _279_ = ~_278_;
  assign _280_ = _232_ & _278_;
  assign _281_ = _233_ | _279_;
  assign _282_ = _230_ | _280_;
  assign _283_ = _228_ | _282_;
  assign _017_ = ~_283_;
  assign _018_ = _228_ & _282_;
  assign _019_ = _225_ & _226_;
  assign _020_ = _284_ | _285_;
  assign _021_ = _224_ & _019_;
  assign _022_ = _286_ | _020_;
  assign _023_ = _018_ | _022_;
  assign _024_ = _017_ | _023_;
  assign _025_ = _001_ & _000_;
  assign _026_ = _002_ & _025_;
  assign _027_ = _003_ & _026_;
  assign _028_ = _004_ & _027_;
  assign _029_ = _005_ & _028_;
  assign _030_ = ~_029_;
  assign _031_ = _225_ & _285_;
  assign _032_ = _286_ & _031_;
  assign _033_ = _006_ & _029_;
  assign _034_ = _006_ ^ _029_;
  assign _035_ = _032_ & _034_;
  assign _036_ = _218_ & _223_;
  assign _037_ = _220_ & _036_;
  assign _038_ = _221_ & _037_;
  assign _039_ = _216_ & _038_;
  assign _040_ = _222_ & _039_;
  assign _041_ = _219_ & _040_;
  assign _042_ = _006_ ^ _040_;
  assign _043_ = _284_ & _285_;
  assign _044_ = _286_ & _043_;
  assign _045_ = _042_ & _044_;
  assign _046_ = _006_ | _014_;
  assign _047_ = _224_ & _043_;
  assign _048_ = _286_ & _019_;
  assign _049_ = _006_ & _014_;
  assign _050_ = _046_ & _047_;
  assign _051_ = _228_ & _048_;
  assign _052_ = _050_ | _051_;
  assign _053_ = _224_ & _031_;
  assign _054_ = _049_ & _053_;
  assign _055_ = _286_ & _264_;
  assign _056_ = _219_ & _055_;
  assign _057_ = _054_ | _056_;
  assign _058_ = _052_ | _057_;
  assign _059_ = _035_ | _058_;
  assign _060_ = _045_ | _059_;
  assign _061_ = ~_060_;
  assign _062_ = _024_ & _061_;
  assign _063_ = _270_ & _062_;
  assign _294_ = ~_063_;
  assign _064_ = _232_ ^ _261_;
  assign _065_ = _265_ & _064_;
  assign _066_ = _232_ | _278_;
  assign _067_ = _021_ & _066_;
  assign _068_ = _281_ & _067_;
  assign _069_ = _005_ ^ _039_;
  assign _070_ = _044_ & _069_;
  assign _071_ = _005_ | _028_;
  assign _072_ = _032_ & _071_;
  assign _073_ = _030_ & _072_;
  assign _074_ = _232_ & _048_;
  assign _075_ = _231_ & _047_;
  assign _076_ = _074_ | _075_;
  assign _077_ = _222_ & _055_;
  assign _078_ = _230_ & _053_;
  assign _079_ = _077_ | _078_;
  assign _080_ = _076_ | _079_;
  assign _081_ = _073_ | _080_;
  assign _082_ = _070_ | _081_;
  assign _083_ = _068_ | _082_;
  assign _293_ = _065_ | _083_;
  assign _084_ = _237_ ^ _259_;
  assign _085_ = _265_ & _084_;
  assign _086_ = _237_ ^ _276_;
  assign _087_ = _021_ & _086_;
  assign _088_ = _004_ ^ _027_;
  assign _089_ = _032_ & _088_;
  assign _090_ = _236_ & _047_;
  assign _091_ = _216_ & _055_;
  assign _092_ = _237_ & _048_;
  assign _093_ = _235_ & _053_;
  assign _094_ = _090_ | _092_;
  assign _095_ = _091_ | _093_;
  assign _096_ = _094_ | _095_;
  assign _097_ = _004_ ^ _038_;
  assign _098_ = _044_ & _097_;
  assign _099_ = _096_ | _098_;
  assign _100_ = _089_ | _099_;
  assign _101_ = _087_ | _100_;
  assign _292_ = _085_ | _101_;
  assign _102_ = _241_ ^ _257_;
  assign _103_ = _265_ & _102_;
  assign _104_ = _241_ ^ _274_;
  assign _105_ = _021_ & _104_;
  assign _106_ = _003_ ^ _026_;
  assign _107_ = _032_ & _106_;
  assign _108_ = _003_ ^ _037_;
  assign _109_ = _044_ & _108_;
  assign _110_ = _239_ & _053_;
  assign _111_ = _240_ & _047_;
  assign _112_ = _221_ & _055_;
  assign _113_ = _241_ & _048_;
  assign _114_ = _111_ | _113_;
  assign _115_ = _110_ | _112_;
  assign _116_ = _114_ | _115_;
  assign _117_ = _109_ | _116_;
  assign _118_ = _107_ | _117_;
  assign _119_ = _105_ | _118_;
  assign _291_ = _103_ | _119_;
  assign _120_ = _245_ ^ _255_;
  assign _121_ = _265_ & _120_;
  assign _122_ = _245_ ^ _272_;
  assign _123_ = _021_ & _122_;
  assign _124_ = _245_ & _048_;
  assign _125_ = _244_ & _047_;
  assign _126_ = _002_ ^ _025_;
  assign _127_ = _032_ & _126_;
  assign _128_ = _002_ ^ _036_;
  assign _129_ = _044_ & _128_;
  assign _130_ = _243_ & _053_;
  assign _131_ = _220_ & _055_;
  assign _132_ = _124_ | _131_;
  assign _133_ = _127_ | _132_;
  assign _134_ = _125_ | _130_;
  assign _135_ = _129_ | _134_;
  assign _136_ = _133_ | _135_;
  assign _137_ = _123_ | _136_;
  assign _290_ = _121_ | _137_;
  assign _138_ = _249_ ^ _253_;
  assign _139_ = _265_ & _138_;
  assign _140_ = _224_ & _250_;
  assign _141_ = _249_ ^ _140_;
  assign _142_ = _019_ & _141_;
  assign _143_ = _025_ | _036_;
  assign _144_ = _248_ & _047_;
  assign _145_ = _247_ & _053_;
  assign _146_ = _218_ & _055_;
  assign _147_ = _145_ | _146_;
  assign _148_ = _142_ | _147_;
  assign _149_ = _143_ ? _044_ : _032_;
  assign _150_ = _144_ | _149_;
  assign _151_ = _139_ | _150_;
  assign _289_ = _148_ | _151_;
  assign _152_ = _265_ | _019_;
  assign _153_ = _252_ & _152_;
  assign _154_ = _031_ & _140_;
  assign _155_ = _251_ & _047_;
  assign _156_ = _286_ & _020_;
  assign _157_ = _223_ & _156_;
  assign _158_ = _155_ | _157_;
  assign _159_ = _154_ | _158_;
  assign _288_ = _153_ | _159_;
  assign _160_ = _015_ & _217_;
  assign _161_ = _215_ & _007_;
  assign _162_ = _015_ | _217_;
  assign _163_ = _160_ | _161_;
  assign _164_ = ~_163_;
  assign _165_ = _227_ & _267_;
  assign _166_ = _164_ ^ _165_;
  assign _167_ = _266_ | _166_;
  assign _168_ = _018_ | _049_;
  assign _169_ = _164_ ^ _168_;
  assign _170_ = _015_ & _007_;
  assign _171_ = _015_ | _007_;
  assign _172_ = _168_ & _171_;
  assign _173_ = ~_172_;
  assign _174_ = _022_ | _169_;
  assign _175_ = _007_ & _033_;
  assign _176_ = _007_ ^ _033_;
  assign _177_ = _032_ & _176_;
  assign _178_ = _217_ & _044_;
  assign _179_ = _041_ & _178_;
  assign _180_ = _007_ & _044_;
  assign _181_ = _048_ & _163_;
  assign _182_ = _047_ & _171_;
  assign _183_ = _181_ | _182_;
  assign _184_ = _217_ & _055_;
  assign _185_ = _053_ & _170_;
  assign _186_ = _184_ | _185_;
  assign _187_ = _183_ | _186_;
  assign _188_ = _041_ ? _178_ : _180_;
  assign _189_ = _177_ | _187_;
  assign _190_ = _188_ | _189_;
  assign _191_ = ~_190_;
  assign _192_ = _174_ & _191_;
  assign _193_ = _167_ & _192_;
  assign _295_ = ~_193_;
  assign _194_ = _168_ | _170_;
  assign _195_ = _021_ & _194_;
  assign _196_ = _171_ & _195_;
  assign _197_ = _267_ | _163_;
  assign _198_ = _227_ | _160_;
  assign _199_ = _265_ & _198_;
  assign _200_ = _162_ & _199_;
  assign _201_ = _197_ & _200_;
  assign _202_ = _032_ & _175_;
  assign _203_ = _179_ | _202_;
  assign _204_ = _201_ | _203_;
  assign _016_ = _196_ | _204_;
  assign _205_ = _173_ & _195_;
  assign _206_ = _165_ ? _161_ : _160_;
  assign _207_ = _265_ & _206_;
  assign _287_ = _205_ | _207_;
  assign _208_ = _289_ | _288_;
  assign _209_ = _290_ | _208_;
  assign _210_ = _291_ | _209_;
  assign _211_ = _292_ | _210_;
  assign _212_ = _293_ | _211_;
  assign _213_ = ~_212_;
  assign _214_ = _063_ & _213_;
  assign _296_ = _193_ & _214_;
  assign { _446_[8], _446_[0] } = { _444_[7], _445_[0] };
  assign _441_[8] = 1'h0;
  assign { _444_[8], _444_[0] } = { 1'h0, A[0] };
  assign _445_[8:1] = { 1'h0, A[7:1] };
  assign { _443_[8], _443_[0] } = { 1'h0, _440_[0] };
  assign _325_[0] = _305_;
  assign _319_[0] = _316_;
  assign _454_[0] = _445_[0];
  assign _452_[0] = A[0];
  assign _453_[0] = A[0];
  assign { _442_[8], _442_[0] } = { _440_[7], _441_[0] };
  assign _440_[8] = 1'h0;
  assign _015_ = B[7];
  assign _004_ = A[4];
  assign _007_ = A[7];
  assign _001_ = A[1];
  assign _006_ = A[6];
  assign _002_ = A[2];
  assign _003_ = A[3];
  assign _005_ = A[5];
  assign _000_ = A[0];
  assign _008_ = B[0];
  assign _014_ = B[6];
  assign _012_ = B[4];
  assign _011_ = B[3];
  assign _013_ = B[5];
  assign _286_ = opcode[2];
  assign _284_ = opcode[0];
  assign _285_ = opcode[1];
  assign _010_ = B[2];
  assign _009_ = B[1];
  assign result[6] = _294_;
  assign result[5] = _293_;
  assign result[4] = _292_;
  assign result[3] = _291_;
  assign result[2] = _290_;
  assign result[1] = _289_;
  assign result[0] = _288_;
  assign result[7] = _295_;
  assign carry = _016_;
  assign overflow = _287_;
  assign zero = _296_;
endmodule
