/* Generated by Yosys 0.69+post (git sha1 143eb14f9cc55d6f8927e68523b0c9d2166ed02c, Release, AppleClang clang++ 21.0.0.21000334) */

(* top =  1  *)
(* src = "rtl/alu_8bit.v:1.1-88.10" *)
module alu_8bit(A, B, opcode, result, zero, carry, overflow);
  (* src = "rtl/alu_8bit.v:2.18-2.19" *)
  input [7:0] A;
  wire [7:0] A;
  (* src = "rtl/alu_8bit.v:3.18-3.19" *)
  input [7:0] B;
  wire [7:0] B;
  (* src = "rtl/alu_8bit.v:4.18-4.24" *)
  input [2:0] opcode;
  wire [2:0] opcode;
  (* src = "rtl/alu_8bit.v:6.22-6.28" *)
  output [7:0] result;
  wire [7:0] result;
  (* src = "rtl/alu_8bit.v:7.22-7.26" *)
  output zero;
  wire zero;
  (* src = "rtl/alu_8bit.v:8.22-8.27" *)
  output carry;
  wire carry;
  (* src = "rtl/alu_8bit.v:9.22-9.30" *)
  output overflow;
  wire overflow;
  (* src = "rtl/alu_8bit.v:31.24-31.61" *)
  wire _000_;
  (* src = "rtl/alu_8bit.v:42.24-42.58" *)
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire [2:0] _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire [3:0] _013_;
  wire [1:0] _014_;
  wire _015_;
  wire [3:0] _016_;
  wire [1:0] _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire [1:0] _022_;
  wire _023_;
  wire _024_;
  wire [1:0] _025_;
  wire _026_;
  wire _027_;
  wire [1:0] _028_;
  wire _029_;
  wire [3:0] _030_;
  wire [1:0] _031_;
  wire _032_;
  wire [3:0] _033_;
  wire [1:0] _034_;
  wire _035_;
  wire [3:0] _036_;
  wire [1:0] _037_;
  wire _038_;
  wire [3:0] _039_;
  wire [1:0] _040_;
  wire _041_;
  wire [3:0] _042_;
  wire [1:0] _043_;
  wire _044_;
  wire [3:0] _045_;
  wire [1:0] _046_;
  wire _047_;
  wire [3:0] _048_;
  wire [1:0] _049_;
  wire _050_;
  wire [3:0] _051_;
  wire [1:0] _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire _117_;
  wire _118_;
  wire _119_;
  wire _120_;
  wire _121_;
  wire _122_;
  wire _123_;
  wire _124_;
  wire _125_;
  wire _126_;
  wire _127_;
  wire _128_;
  wire _129_;
  wire _130_;
  (* src = "rtl/alu_8bit.v:75.23-75.32" *)
  wire _131_;
  (* src = "rtl/alu_8bit.v:39.22-39.27" *)
  wire _132_;
  (* src = "rtl/alu_8bit.v:31.25-31.39" *)
  wire _133_;
  (* src = "rtl/alu_8bit.v:52.22-52.27" *)
  wire [7:0] _134_;
  wire _135_;
  wire _136_;
  wire _137_;
  wire _138_;
  wire _139_;
  wire _140_;
  wire _141_;
  wire _142_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [8:0] _143_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [8:0] _144_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [8:0] _145_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [8:0] _146_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [8:0] _147_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [8:0] _148_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [8:0] _149_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.21-279.23" *)
  wire [7:0] _150_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [7:0] _151_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _152_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _153_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:200.21-200.22" *)
  wire [7:0] _154_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:274.23-274.25" *)
  wire [7:0] _155_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:287.21-287.22" *)
  wire [7:0] _156_;
  (* force_downto = 32'd1 *)
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [7:0] _157_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _158_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _159_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _160_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _161_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _162_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _163_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _164_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _165_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _166_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _167_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _168_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _169_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _170_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _171_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _172_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _173_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _174_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _175_;
  (* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _176_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _177_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _178_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _179_;
  (* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _180_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _181_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _182_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _183_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _184_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _185_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _186_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _187_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _188_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _189_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _190_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _191_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _192_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _193_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _194_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _195_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _196_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _197_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _198_;
  (* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _199_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _200_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _201_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _202_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)
  wire _203_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _204_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)
  wire _205_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _206_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _207_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _208_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)
  wire _209_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _210_;
  (* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)
  wire _211_;
  (* src = "rtl/alu_8bit.v:31.44-31.60" *)
  wire _212_;
  (* src = "rtl/alu_8bit.v:42.41-42.57" *)
  wire _213_;
  assign _156_[1] = ~A[1];
  assign _156_[3] = ~A[3];
  assign _156_[2] = ~A[2];
  assign _156_[4] = ~A[4];
  assign _156_[5] = ~A[5];
  assign _156_[7] = ~A[7];
  assign _156_[6] = ~A[6];
  assign _148_[0] = ~A[0];
  assign _153_[0] = ~_152_[0];
  assign _004_ = ~opcode[0];
  assign _005_ = ~opcode[1];
  assign _006_ = ~opcode[2];
  assign _151_[4] = _154_[4] |(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _194_;
  assign _181_ = _152_[1] &(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _151_[0];
  assign _151_[0] = _154_[0] |(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:231.10-231.28" *)  _152_[0];
  assign _147_[4] = A[4] &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _147_[3];
  assign _147_[2] = A[2] &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _147_[1];
  assign _147_[6] = A[6] &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _147_[5];
  assign _147_[5] = _178_ &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _147_[3];
  assign _147_[7] = _180_ &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _147_[3];
  assign _180_ = _179_ &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _178_;
  assign _147_[3] = _177_ &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _147_[1];
  assign _179_ = A[7] &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  A[6];
  assign _178_ = A[5] &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  A[4];
  assign _177_ = A[3] &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  A[2];
  assign _147_[1] = A[1] &(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[0];
  assign _155_[2] = A[2] |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _207_;
  assign _207_ = _156_[2] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _155_[1];
  assign _208_ = _156_[4] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _155_[3];
  assign _155_[5] = _211_ |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _206_;
  assign _206_ = _205_ &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _155_[3];
  assign _209_ = _156_[6] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _155_[5];
  assign _155_[6] = A[6] |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _209_;
  assign _155_[3] = _210_ |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _203_;
  assign _203_ = _204_ &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _155_[1];
  assign _205_ = _156_[5] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _156_[4];
  assign _211_ = A[5] |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _202_;
  assign _202_ = _156_[5] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[4];
  assign _204_ = _156_[3] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _156_[2];
  assign _210_ = A[3] |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _201_;
  assign _201_ = _156_[3] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[2];
  assign _155_[4] = A[4] |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _208_;
  assign _155_[1] = A[1] |(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _200_;
  assign _200_ = _156_[1] &(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  A[0];
  assign _212_ = _145_[7] ^(* src = "rtl/alu_8bit.v:31.44-31.60" *)  A[7];
  assign _000_ = _133_ &(* src = "rtl/alu_8bit.v:31.24-31.61" *)  _212_;
  assign _213_ = _153_[7] ^(* src = "rtl/alu_8bit.v:42.41-42.57" *)  A[7];
  assign _001_ = _144_[7] &(* src = "rtl/alu_8bit.v:42.24-42.58" *)  _213_;
  assign _134_[0] = A[0] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[0];
  assign _134_[1] = A[1] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[1];
  assign _134_[2] = A[2] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[2];
  assign _134_[3] = A[3] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[3];
  assign _134_[4] = A[4] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[4];
  assign _134_[5] = A[5] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[5];
  assign _134_[6] = A[6] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[6];
  assign _134_[7] = A[7] |(* src = "rtl/alu_8bit.v:52.22-52.27" *)  B[7];
  assign _145_[1] = _144_[1] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _143_[0];
  assign _145_[2] = _144_[2] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _143_[1];
  assign _145_[3] = _144_[3] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _143_[2];
  assign _145_[4] = _144_[4] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _143_[3];
  assign _145_[5] = _144_[5] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _143_[4];
  assign _145_[6] = _144_[6] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _143_[5];
  assign _145_[7] = _144_[7] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _143_[6];
  assign _153_[1] = _152_[1] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _151_[0];
  assign _153_[2] = _152_[2] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _151_[1];
  assign _153_[3] = _152_[3] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _151_[2];
  assign _153_[4] = _152_[4] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _151_[3];
  assign _153_[5] = _152_[5] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _151_[4];
  assign _153_[6] = _152_[6] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _151_[5];
  assign _153_[7] = _152_[7] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _151_[6];
  assign _149_[1] = A[1] ^(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  A[0];
  assign _149_[2] = A[2] ^(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _147_[1];
  assign _149_[3] = A[3] ^(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _147_[2];
  assign _149_[4] = A[4] ^(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _147_[3];
  assign _149_[5] = A[5] ^(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _147_[4];
  assign _149_[6] = A[6] ^(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _147_[5];
  assign _149_[7] = A[7] ^(* src = "rtl/alu_8bit.v:67.22-67.38|rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _147_[6];
  assign _157_[1] = _156_[1] ^(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  A[0];
  assign _157_[2] = _156_[2] ^(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _155_[1];
  assign _157_[3] = _156_[3] ^(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _155_[2];
  assign _157_[4] = _156_[4] ^(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _155_[3];
  assign _157_[5] = _156_[5] ^(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _155_[4];
  assign _157_[6] = _156_[6] ^(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _155_[5];
  assign _157_[7] = _156_[7] ^(* src = "rtl/alu_8bit.v:74.22-74.30|rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:296.13-296.25" *)  _155_[6];
  assign _143_[0] = A[0] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[0];
  assign _146_[1] = A[1] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[1];
  assign _146_[2] = A[2] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[2];
  assign _146_[3] = A[3] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[3];
  assign _146_[4] = A[4] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[4];
  assign _146_[5] = A[5] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[5];
  assign _146_[6] = A[6] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[6];
  assign _146_[7] = A[7] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  B[7];
  assign _144_[0] = A[0] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[0];
  assign _144_[1] = A[1] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[1];
  assign _144_[2] = A[2] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[2];
  assign _144_[3] = A[3] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[3];
  assign _144_[4] = A[4] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[4];
  assign _144_[5] = A[5] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[5];
  assign _144_[6] = A[6] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[6];
  assign _144_[7] = A[7] ^(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  B[7];
  assign _171_ = _144_[4] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _143_[3];
  assign _143_[6] = _146_[6] |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _172_;
  assign _143_[2] = _146_[2] |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _170_;
  assign _170_ = _144_[2] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _143_[1];
  assign _172_ = _144_[6] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _143_[5];
  assign _143_[5] = _174_ |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _169_;
  assign _169_ = _166_ &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _143_[3];
  assign _143_[7] = _176_ |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _164_;
  assign _164_ = _168_ &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _143_[3];
  assign _168_ = _167_ &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _166_;
  assign _176_ = _175_ |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _163_;
  assign _163_ = _167_ &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _174_;
  assign _143_[3] = _173_ |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _162_;
  assign _162_ = _165_ &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _143_[1];
  assign _167_ = _144_[7] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _144_[6];
  assign _175_ = _146_[7] |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _161_;
  assign _161_ = _144_[7] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _146_[6];
  assign _166_ = _144_[5] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _144_[4];
  assign _174_ = _146_[5] |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _160_;
  assign _160_ = _144_[5] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _146_[4];
  assign _165_ = _144_[3] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _144_[2];
  assign _173_ = _146_[3] |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _159_;
  assign _159_ = _144_[3] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _146_[2];
  assign _143_[4] = _146_[4] |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _171_;
  assign _143_[1] = _146_[1] |(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _158_;
  assign _158_ = _144_[1] &(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _143_[0];
  assign _154_[1] = A[1] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[1];
  assign _154_[4] = A[4] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[4];
  assign _154_[6] = A[6] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[6];
  assign _152_[0] = A[0] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[0];
  assign _152_[2] = A[2] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[2];
  assign _152_[4] = A[4] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[4];
  assign _152_[6] = A[6] ^(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[6];
  assign _151_[2] = _154_[2] |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _193_;
  assign _193_ = _152_[2] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _151_[1];
  assign _194_ = _152_[4] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _151_[3];
  assign _151_[5] = _197_ |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _192_;
  assign _192_ = _189_ &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _151_[3];
  assign _195_ = _152_[6] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.19-248.41" *)  _151_[5];
  assign _151_[7] = _199_ |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _187_;
  assign _187_ = _191_ &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _151_[3];
  assign _191_ = _190_ &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _189_;
  assign _199_ = _198_ |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _186_;
  assign _186_ = _190_ &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _197_;
  assign _151_[6] = _154_[6] |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:248.12-248.41" *)  _195_;
  assign _151_[3] = _196_ |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _185_;
  assign _185_ = _188_ &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _151_[1];
  assign _190_ = _152_[7] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _152_[6];
  assign _198_ = _154_[7] |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _184_;
  assign _184_ = _152_[7] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _154_[6];
  assign _189_ = _152_[5] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _152_[4];
  assign _197_ = _154_[5] |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _183_;
  assign _183_ = _152_[5] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _154_[4];
  assign _188_ = _152_[3] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:241.12-241.34" *)  _152_[2];
  assign _196_ = _154_[3] |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _182_;
  assign _182_ = _152_[3] &(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.19-240.41" *)  _154_[2];
  assign _151_[1] = _154_[1] |(* src = "rtl/alu_8bit.v:36.22-36.27|/opt/homebrew/bin/../share/yosys/techmap.v:293.27-293.63|/opt/homebrew/bin/../share/yosys/techmap.v:240.12-240.41" *)  _181_;
  assign _154_[0] = A[0] &(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[0];
  assign _154_[2] = A[2] &(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[2];
  assign _154_[3] = A[3] &(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[3];
  assign _154_[5] = A[5] &(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[5];
  assign _154_[7] = A[7] &(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.26-205.31" *)  _150_[7];
  assign _152_[1] = A[1] ^(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[1];
  assign _152_[3] = A[3] ^(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[3];
  assign _152_[5] = A[5] ^(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[5];
  assign _152_[7] = A[7] ^(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:292.26-292.70|/opt/homebrew/bin/../share/yosys/techmap.v:205.14-205.19" *)  _150_[7];
  assign _003_ = _008_ | _007_[2];
  assign _002_ = _007_[1] | _007_[2];
  assign _055_ = _009_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _006_;
  assign _056_ = _010_ |(* src = "rtl/alu_8bit.v:63.12-63.12|rtl/alu_8bit.v:22.5-78.12" *)  _006_;
  assign _057_ = _011_ |(* src = "rtl/alu_8bit.v:58.12-58.12|rtl/alu_8bit.v:22.5-78.12" *)  _006_;
  assign _058_ = _012_ |(* src = "rtl/alu_8bit.v:53.12-53.12|rtl/alu_8bit.v:22.5-78.12" *)  _006_;
  assign _009_ = _004_ |(* src = "rtl/alu_8bit.v:48.12-48.12|rtl/alu_8bit.v:22.5-78.12" *)  _005_;
  assign _059_ = _009_ |(* src = "rtl/alu_8bit.v:48.12-48.12|rtl/alu_8bit.v:22.5-78.12" *)  opcode[2];
  assign _010_ = opcode[0] |(* src = "rtl/alu_8bit.v:43.12-43.12|rtl/alu_8bit.v:22.5-78.12" *)  _005_;
  assign _060_ = _010_ |(* src = "rtl/alu_8bit.v:43.12-43.12|rtl/alu_8bit.v:22.5-78.12" *)  opcode[2];
  assign _011_ = _004_ |(* src = "rtl/alu_8bit.v:32.12-32.12|rtl/alu_8bit.v:22.5-78.12" *)  opcode[1];
  assign _061_ = _011_ |(* src = "rtl/alu_8bit.v:32.12-32.12|rtl/alu_8bit.v:22.5-78.12" *)  opcode[2];
  assign _013_[0] = A[0] |(* src = "rtl/alu_8bit.v:75.23-75.32" *)  A[1];
  assign _013_[1] = A[2] |(* src = "rtl/alu_8bit.v:75.23-75.32" *)  A[3];
  assign _013_[2] = A[4] |(* src = "rtl/alu_8bit.v:75.23-75.32" *)  A[5];
  assign _013_[3] = A[6] |(* src = "rtl/alu_8bit.v:75.23-75.32" *)  A[7];
  assign _014_[0] = _013_[0] |(* src = "rtl/alu_8bit.v:75.23-75.32" *)  _013_[1];
  assign _014_[1] = _013_[2] |(* src = "rtl/alu_8bit.v:75.23-75.32" *)  _013_[3];
  assign _015_ = _014_[0] |(* src = "rtl/alu_8bit.v:75.23-75.32" *)  _014_[1];
  assign _016_[0] = result[0] |(* src = "rtl/alu_8bit.v:81.9-81.23" *)  result[1];
  assign _016_[1] = result[2] |(* src = "rtl/alu_8bit.v:81.9-81.23" *)  result[3];
  assign _016_[2] = result[4] |(* src = "rtl/alu_8bit.v:81.9-81.23" *)  result[5];
  assign _016_[3] = result[6] |(* src = "rtl/alu_8bit.v:81.9-81.23" *)  result[7];
  assign _017_[0] = _016_[0] |(* src = "rtl/alu_8bit.v:81.9-81.23" *)  _016_[1];
  assign _017_[1] = _016_[2] |(* src = "rtl/alu_8bit.v:81.9-81.23" *)  _016_[3];
  assign _018_ = _017_[0] |(* src = "rtl/alu_8bit.v:81.9-81.23" *)  _017_[1];
  assign _020_ = _019_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _003_;
  assign _021_ = _062_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _063_;
  assign _022_[1] = _002_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _023_ = _019_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _022_[1];
  assign _024_ = _023_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _025_[0] = _064_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _065_;
  assign _026_ = _025_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _025_[1];
  assign _027_ = _026_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _066_;
  assign _007_[0] = _135_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _007_[1] = _137_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _007_[2] = _139_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _019_ = _141_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _008_ = _007_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _007_[1];
  assign _028_[1] = _007_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _019_;
  assign _029_ = _008_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _028_[1];
  assign _030_[0] = _067_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _068_;
  assign _030_[1] = _069_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _070_;
  assign _030_[2] = _071_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _072_;
  assign _030_[3] = _073_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _074_;
  assign _031_[0] = _030_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _030_[1];
  assign _031_[1] = _030_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _030_[3];
  assign _032_ = _031_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _031_[1];
  assign _033_[0] = _075_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _076_;
  assign _033_[1] = _077_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _078_;
  assign _033_[2] = _079_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _080_;
  assign _033_[3] = _081_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _082_;
  assign _034_[0] = _033_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _033_[1];
  assign _034_[1] = _033_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _033_[3];
  assign _035_ = _034_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _034_[1];
  assign _036_[0] = _083_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _084_;
  assign _036_[1] = _085_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _086_;
  assign _036_[2] = _087_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _088_;
  assign _036_[3] = _089_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _090_;
  assign _037_[0] = _036_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _036_[1];
  assign _037_[1] = _036_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _036_[3];
  assign _038_ = _037_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _037_[1];
  assign _039_[0] = _091_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _092_;
  assign _039_[1] = _093_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _094_;
  assign _039_[2] = _095_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _096_;
  assign _039_[3] = _097_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _098_;
  assign _040_[0] = _039_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _039_[1];
  assign _040_[1] = _039_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _039_[3];
  assign _041_ = _040_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _040_[1];
  assign _042_[0] = _099_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _100_;
  assign _042_[1] = _101_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _102_;
  assign _042_[2] = _103_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _104_;
  assign _042_[3] = _105_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _106_;
  assign _043_[0] = _042_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _042_[1];
  assign _043_[1] = _042_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _042_[3];
  assign _044_ = _043_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _043_[1];
  assign _045_[0] = _107_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _108_;
  assign _045_[1] = _109_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _110_;
  assign _045_[2] = _111_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _112_;
  assign _045_[3] = _113_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _114_;
  assign _046_[0] = _045_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _045_[1];
  assign _046_[1] = _045_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _045_[3];
  assign _047_ = _046_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _046_[1];
  assign _048_[0] = _115_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _116_;
  assign _048_[1] = _117_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _118_;
  assign _048_[2] = _119_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _120_;
  assign _048_[3] = _121_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _122_;
  assign _049_[0] = _048_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _048_[1];
  assign _049_[1] = _048_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _048_[3];
  assign _050_ = _049_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _049_[1];
  assign _051_[0] = _123_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _124_;
  assign _051_[1] = _125_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _126_;
  assign _051_[2] = _127_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _128_;
  assign _051_[3] = _129_ |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _130_;
  assign _052_[0] = _051_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _051_[1];
  assign _052_[1] = _051_[2] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _051_[3];
  assign _053_ = _052_[0] |(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _052_[1];
  assign _012_ = opcode[0] |(* src = "rtl/alu_8bit.v:22.18-22.18|rtl/alu_8bit.v:22.5-78.12" *)  opcode[1];
  assign _054_ = _012_ |(* src = "rtl/alu_8bit.v:22.18-22.18|rtl/alu_8bit.v:22.5-78.12" *)  opcode[2];
  assign _131_ = ~(* src = "rtl/alu_8bit.v:75.23-75.32" *) _015_;
  assign _135_ = ~(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _055_;
  assign _136_ = ~(* src = "rtl/alu_8bit.v:63.12-63.12|rtl/alu_8bit.v:22.5-78.12" *) _056_;
  assign _137_ = ~(* src = "rtl/alu_8bit.v:58.12-58.12|rtl/alu_8bit.v:22.5-78.12" *) _057_;
  assign _138_ = ~(* src = "rtl/alu_8bit.v:53.12-53.12|rtl/alu_8bit.v:22.5-78.12" *) _058_;
  assign _139_ = ~(* src = "rtl/alu_8bit.v:48.12-48.12|rtl/alu_8bit.v:22.5-78.12" *) _059_;
  assign _140_ = ~(* src = "rtl/alu_8bit.v:43.12-43.12|rtl/alu_8bit.v:22.5-78.12" *) _060_;
  assign _141_ = ~(* src = "rtl/alu_8bit.v:32.12-32.12|rtl/alu_8bit.v:22.5-78.12" *) _061_;
  assign _142_ = ~(* src = "rtl/alu_8bit.v:22.18-22.18|rtl/alu_8bit.v:22.5-78.12" *) _054_;
  assign zero = ~(* src = "rtl/alu_8bit.v:81.9-81.23|rtl/alu_8bit.v:81.5-84.21" *) _018_;
  assign _062_ = _000_ &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _063_ = _001_ &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _064_ = _143_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _065_ = _132_ &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _025_[1] = _147_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _066_ = _131_ &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _067_ = _148_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _068_ = _148_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _069_ = _148_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _070_ = _144_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _071_ = _134_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _072_ = _143_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _073_ = _153_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _074_ = _144_[0] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _075_ = _157_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _076_ = _149_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _077_ = _156_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _078_ = _144_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _079_ = _134_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _080_ = _146_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _081_ = _153_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _082_ = _145_[1] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _083_ = _157_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _084_ = _149_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _085_ = _156_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _086_ = _144_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _087_ = _134_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _088_ = _146_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _089_ = _153_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _090_ = _145_[2] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _091_ = _157_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _092_ = _149_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _093_ = _156_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _094_ = _144_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _095_ = _134_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _096_ = _146_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _097_ = _153_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _098_ = _145_[3] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _099_ = _157_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _100_ = _149_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _101_ = _156_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _102_ = _144_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _103_ = _134_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _104_ = _146_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _105_ = _153_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _106_ = _145_[4] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _107_ = _157_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _108_ = _149_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _109_ = _156_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _110_ = _144_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _111_ = _134_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _112_ = _146_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _113_ = _153_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _114_ = _145_[5] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _115_ = _157_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _116_ = _149_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _117_ = _156_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _118_ = _144_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _119_ = _134_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _120_ = _146_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _121_ = _153_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _122_ = _145_[6] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _123_ = _157_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _135_;
  assign _124_ = _149_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _136_;
  assign _125_ = _156_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _137_;
  assign _126_ = _144_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _138_;
  assign _127_ = _134_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _139_;
  assign _128_ = _146_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _140_;
  assign _129_ = _153_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _141_;
  assign _130_ = _145_[7] &(* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *)  _142_;
  assign _133_ = ~(* src = "rtl/alu_8bit.v:31.25-31.39" *) _144_[7];
  assign _132_ = ~(* src = "rtl/alu_8bit.v:39.22-39.27" *) _151_[7];
  assign _150_[7] = ~(* src = "rtl/alu_8bit.v:26.22-26.43|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[7];
  assign _150_[0] = ~(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[0];
  assign _150_[1] = ~(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[1];
  assign _150_[2] = ~(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[2];
  assign _150_[3] = ~(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[3];
  assign _150_[4] = ~(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[4];
  assign _150_[5] = ~(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[5];
  assign _150_[6] = ~(* src = "rtl/alu_8bit.v:39.22-39.27|/opt/homebrew/bin/../share/yosys/techmap.v:279.31-279.37" *) B[6];
  assign overflow = _020_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _021_ : 1'hx;
  assign carry = _024_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _027_ : 1'hx;
  assign result[0] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _032_ : 1'hx;
  assign result[1] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _035_ : 1'hx;
  assign result[2] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _038_ : 1'hx;
  assign result[3] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _041_ : 1'hx;
  assign result[4] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _044_ : 1'hx;
  assign result[5] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _047_ : 1'hx;
  assign result[6] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _050_ : 1'hx;
  assign result[7] = _029_ ? (* src = "rtl/alu_8bit.v:70.12-70.12|rtl/alu_8bit.v:22.5-78.12" *) _053_ : 1'hx;
  assign { _149_[8], _149_[0] } = { _147_[7], _148_[0] };
  assign _144_[8] = 1'h0;
  assign { _147_[8], _147_[0] } = { 1'h0, A[0] };
  assign _148_[8:1] = { 1'h0, A[7:1] };
  assign { _146_[8], _146_[0] } = { 1'h0, _143_[0] };
  assign _028_[0] = _008_;
  assign _022_[0] = _019_;
  assign _157_[0] = _148_[0];
  assign _155_[0] = A[0];
  assign _156_[0] = A[0];
  assign { _145_[8], _145_[0] } = { _143_[7], _144_[0] };
  assign _143_[8] = 1'h0;
endmodule
